[dependencies]
biome_console = { workspace = true }
biome_deserialize = { workspace = true }
biome_deserialize_macros = { workspace = true }
biome_diagnostics = { workspace = true }
biome_rowan = { workspace = true }
biome_string_case = { workspace = true }
camino = { workspace = true }
cfg-if = { workspace = true }
countme = { workspace = true }
drop_bomb = "0.1.5"
indexmap = { workspace = true }
rustc-hash = { workspace = true }
schemars = { workspace = true, optional = true }
serde = { workspace = true, features = ["derive"], optional = true }
tracing = { workspace = true }
unicode-width = { workspace = true }

[dev-dependencies]
biome_js_parser = { path = "../biome_js_parser" }
biome_js_syntax = { path = "../biome_js_syntax" }
insta = { workspace = true }

[features]
schema = ["dep:schemars", "serde"]
serde = ["dep:serde", "biome_deserialize/serde", "biome_rowan/serde"]

[lib]
path = "Source/lib.rs"

[lints]
workspace = true

[package]
description = "Biome's formatter shared infrastructure"
name = "biome_formatter"
version = "0.5.7"

[package.authors]
workspace = true

[package.categories]
workspace = true

[package.edition]
workspace = true

[package.homepage]
workspace = true

[package.keywords]
workspace = true

[package.license-file]
workspace = true

[package.metadata]

[package.metadata.workspaces]
independent = true

[package.repository]
workspace = true
