[dependencies]
biome_diagnostics = { workspace = true }
biome_formatter = { workspace = true }
biome_graphql_syntax = { workspace = true }
biome_rowan = { workspace = true }
biome_suppression = { workspace = true }

[dev-dependencies]
biome_configuration = { path = "../biome_configuration" }
biome_formatter_test = { path = "../biome_formatter_test" }
biome_fs = { path = "../biome_fs" }
biome_graphql_parser = { path = "../biome_graphql_parser" }
biome_parser = { path = "../biome_parser" }
biome_service = { path = "../biome_service" }
camino = { workspace = true }
countme = { workspace = true, features = ["enable"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tests_macros = { path = "../tests_macros" }

[lib]
path = "Source/lib.rs"

[lints]
workspace = true

[package]
description = "Biome's GraphQL formatter"
name = "biome_graphql_formatter"
version = "0.1.0"

[package.authors]
workspace = true

[package.categories]
workspace = true

[package.edition]
workspace = true

[package.homepage]
workspace = true

[package.keywords]
workspace = true

[package.license-file]
workspace = true

[package.metadata]

[package.metadata.workspaces]
independent = true

[package.repository]
workspace = true
