[dependencies]
biome_analyze = { workspace = true }
biome_console = { workspace = true }
biome_diagnostics = { workspace = true }
biome_glob = { workspace = true }
biome_json_factory = { workspace = true }
biome_json_syntax = { workspace = true }
biome_package = { workspace = true }
biome_rowan = { workspace = true }
camino = { workspace = true }
rustc-hash = { workspace = true }

[dev-dependencies]
biome_json_factory = { path = "../biome_json_factory" }
biome_json_formatter = { path = "../biome_json_formatter" }
biome_json_parser = { path = "../biome_json_parser" }
biome_test_utils = { path = "../biome_test_utils" }
insta = { workspace = true, features = ["glob"] }
tests_macros = { path = "../tests_macros" }

[lib]
path = "Source/lib.rs"

[lints]
workspace = true

[package]
description = "Utilities for the `biome migrate` command"
name = "biome_migrate"
publish = false
version = "0.0.0"

[package.authors]
workspace = true

[package.categories]
workspace = true

[package.edition]
workspace = true

[package.homepage]
workspace = true

[package.keywords]
workspace = true

[package.license-file]
workspace = true

[package.repository]
workspace = true
