[dependencies]
biome_package = { workspace = true }
biome_parser = { workspace = true }
camino = { workspace = true }
papaya = { workspace = true }
rustc-hash = { workspace = true }

[lib]
path = "Source/lib.rs"

[lints]
workspace = true

[package]
description = "Data structure for tracking projects and their packages"
name = "biome_project_layout"
version = "0.0.1"

[package.authors]
workspace = true

[package.categories]
workspace = true

[package.edition]
workspace = true

[package.homepage]
workspace = true

[package.keywords]
workspace = true

[package.license]
workspace = true

[package.repository]
workspace = true
