[dependencies]

[dev-dependencies]

[lib]
path = "Source/lib.rs"

[lints]
workspace = true

[package]
description = "Unicode table for JavaScript IDs"
name = "biome_unicode_table"
version = "0.5.7"

[package.authors]
workspace = true

[package.categories]
workspace = true

[package.edition]
workspace = true

[package.homepage]
workspace = true

[package.keywords]
workspace = true

[package.license-file]
workspace = true

[package.repository]
workspace = true
