[build-dependencies]
biome_deserialize = { workspace = true }
biome_deserialize_macros = { workspace = true }
biome_string_case = { workspace = true }
prettyplease = "0.2.30"
proc-macro2 = { workspace = true, features = ["span-locations"] }
quote = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
syn = "2.0.76"

[dependencies]

[lib]
path = "Source/lib.rs"

[lints]
workspace = true

[package]
description = "Metadata about ARIA properties and ARIA roles"
name = "biome_aria_metadata"
version = "0.5.7"

[package.authors]
workspace = true

[package.categories]
workspace = true

[package.edition]
workspace = true

[package.homepage]
workspace = true

[package.keywords]
workspace = true

[package.license-file]
workspace = true

[package.repository]
workspace = true
