[dependencies]
proc-macro-error2 = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }

[lib]
path = "Source/lib.rs"
proc-macro = true

[lints]
workspace = true

[package]
description = "Macros to implement Biome's diagnostics"
name = "biome_diagnostics_macros"
version = "0.5.7"

[package.authors]
workspace = true

[package.categories]
workspace = true

[package.edition]
workspace = true

[package.homepage]
workspace = true

[package.keywords]
workspace = true

[package.license-file]
workspace = true

[package.repository]
workspace = true
