[lib]
path = "Source/lib.rs"

[lints]
workspace = true

[package]
description = "Utilities to convert string cases"
name = "biome_string_case"
version = "0.5.7"

[package.authors]
workspace = true

[package.categories]
workspace = true

[package.edition]
workspace = true

[package.homepage]
workspace = true

[package.keywords]
workspace = true

[package.license-file]
workspace = true

[package.repository]
workspace = true
