[dependencies]
biome_css_syntax = { workspace = true }
biome_rowan = { workspace = true }

[lib]
path = "Source/lib.rs"

[lints]
workspace = true

[package]
description = "Utilities to create CSS AST for biome_css_parser"
name = "biome_css_factory"
version = "0.5.7"

[package.authors]
workspace = true

[package.categories]
workspace = true

[package.edition]
workspace = true

[package.homepage]
workspace = true

[package.keywords]
workspace = true

[package.license-file]
workspace = true

[package.repository]
workspace = true
