[dependencies]
biome_rowan = { workspace = true }
rustc-hash = { workspace = true }

[lib]
path = "Source/lib.rs"

[lints]
workspace = true

[package]
description = "Utilities to build control flow graph for biome_js_analyze"
name = "biome_control_flow"
version = "0.5.7"

[package.authors]
workspace = true

[package.categories]
workspace = true

[package.edition]
workspace = true

[package.homepage]
workspace = true

[package.keywords]
workspace = true

[package.license-file]
workspace = true

[package.repository]
workspace = true
