[dependencies]
biome_markup = { workspace = true }
biome_text_size = { workspace = true }
schemars = { workspace = true, optional = true }
serde = { workspace = true, optional = true, features = ["derive"] }
termcolor = { workspace = true }
unicode-segmentation = "1.12.0"
unicode-width = { workspace = true }

[dev-dependencies]
trybuild = "=1.0.103"

[features]
schema = ["dep:schemars", "serde", "biome_text_size/schema"]
serde = ["dep:serde"]

[lib]
path = "Source/lib.rs"

[lints]
workspace = true

[package]
description = "Utilities to print messages (formatted with biome_markup) and diagnostics"
name = "biome_console"
version = "0.5.7"

[package.authors]
workspace = true

[package.categories]
workspace = true

[package.edition]
workspace = true

[package.homepage]
workspace = true

[package.keywords]
workspace = true

[package.license-file]
workspace = true

[package.repository]
workspace = true
