[dependencies]
biome_deserialize = { workspace = true, features = ["indexmap"] }
biome_deserialize_macros = { workspace = true }
biome_json_syntax = { workspace = true }
biome_rowan = { workspace = true }
indexmap = { workspace = true }
oxc_resolver = { workspace = true, optional = true }
rustc-hash = { workspace = true }
static_assertions = { workspace = true }

[dev-dependencies]
biome_json_parser = { workspace = true }

[features]
oxc_resolver = ["dep:oxc_resolver"]

[lib]
path = "Source/lib.rs"

[lints]
workspace = true

[package]
description = "Mutable JSON values constructable from biome_json_syntax"
name = "biome_json_value"
version = "0.1.0"

[package.authors]
workspace = true

[package.categories]
workspace = true

[package.edition]
workspace = true

[package.homepage]
workspace = true

[package.keywords]
workspace = true

[package.license-file]
workspace = true

[package.repository]
workspace = true
