[dependencies]
biome_rowan = { workspace = true, features = ["serde"] }
biome_string_case = { workspace = true }
camino = { workspace = true }
schemars = { workspace = true, optional = true }
serde = { workspace = true, features = ["derive"] }

[features]
schema = ["schemars", "biome_rowan/serde"]

[lib]
path = "Source/lib.rs"

[lints]
workspace = true

[package]
description = "SyntaxKind and common rowan definitions for biome_grit_parser"
name = "biome_grit_syntax"
version = "0.5.7"

[package.authors]
workspace = true

[package.categories]
workspace = true

[package.edition]
workspace = true

[package.homepage]
workspace = true

[package.keywords]
workspace = true

[package.license-file]
workspace = true

[package.repository]
workspace = true
