[dependencies]
anyhow = { workspace = true }
biome_string_case = { workspace = true }
biome_ungrammar = { workspace = true }
proc-macro2 = { workspace = true, features = ["span-locations"] }
quote = { workspace = true }

[[example]]
name = "minigrammar"

[lib]
path = "Source/lib.rs"

[lints]
workspace = true

[package]
description = "Biome utility to codegen a grammar for the parser"
name = "biome_syntax_codegen"
version = "0.1.0"

[package.authors]
workspace = true

[package.categories]
workspace = true

[package.edition]
workspace = true

[package.homepage]
workspace = true

[package.keywords]
workspace = true

[package.license-file]
workspace = true

[package.repository]
workspace = true
