[dependencies]
biome_css_syntax = { workspace = true }
biome_rowan = { workspace = true }
rustc-hash = { workspace = true }

[lib]
path = "Source/lib.rs"

[lints]
workspace = true

[package]
description = "Biome's semantic model for CSS"
name = "biome_css_semantic"
version = "0.0.0"

[package.authors]
workspace = true

[package.categories]
workspace = true

[package.edition]
workspace = true

[package.homepage]
workspace = true

[package.keywords]
workspace = true

[package.license-file]
workspace = true

[package.repository]
workspace = true
