[dependencies]
anyhow = { workspace = true }
biome_rowan = { workspace = true }
rustc-hash = { workspace = true }
tower-lsp = { version = "0.20.0" }

[dev-dependencies]
tower = { version = "0.4.13", features = ["timeout"] }

[lib]
path = "Source/lib.rs"

[lints]
workspace = true

[package]
description = "Biome's tools to convert between LSP and Biome's data structures"
name = "biome_lsp_converters"
version = "0.1.0"

[package.authors]
workspace = true

[package.categories]
workspace = true

[package.edition]
workspace = true

[package.homepage]
workspace = true

[package.keywords]
workspace = true

[package.license-file]
workspace = true

[package.repository]
workspace = true
