[dependencies]
biome_rowan = { workspace = true }
biome_yaml_syntax = { workspace = true }

[lib]
path = "Source/lib.rs"

[lints]
workspace = true

[package]
description = "Utilities to create YAML AST for biome_yaml_parser"
name = "biome_yaml_factory"
version = "0.0.1"

[package.authors]
workspace = true

[package.categories]
workspace = true

[package.edition]
workspace = true

[package.homepage]
workspace = true

[package.keywords]
workspace = true

[package.license-file]
workspace = true

[package.repository]
workspace = true
