[dependencies]
biome_grit_syntax = { workspace = true }
biome_rowan = { workspace = true }

[lib]
path = "Source/lib.rs"

[lints]
workspace = true

[package]
description = "Utilities to create GritQL AST for biome_grit_parser"
documentation = "https://docs.rs/biome_grit_factory"
name = "biome_grit_factory"
version = "0.5.7"

[package.authors]
workspace = true

[package.edition]
workspace = true

[package.license-file]
workspace = true

[package.repository]
workspace = true
