[dependencies]
biome_text_size = { workspace = true }
schemars = { workspace = true, optional = true }
serde = { workspace = true, features = ["derive"], optional = true }
similar = { workspace = true, features = ["unicode"] }

[features]
schema = ["dep:schemars", "biome_text_size/schema", "serde"]
serde = ["dep:serde", "biome_text_size/serde"]

[lib]
path = "Source/lib.rs"

[lints]
workspace = true

[package]
description = "Utilities to edit text (This is taken from rust-analyzer)"
name = "biome_text_edit"
version = "0.5.7"

[package.authors]
workspace = true

[package.categories]
workspace = true

[package.edition]
workspace = true

[package.homepage]
workspace = true

[package.keywords]
workspace = true

[package.license-file]
workspace = true

[package.repository]
workspace = true
